include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - comment_references
    - directives_ordering
    - lines_longer_than_80_chars
    - prefer_single_quotes
    - require_trailing_commas

  exclude:
    - test/resources/*
    - test/resources/unused_files_analyzer/**
    - test/resources/unused_l10n_analyzer/**
    - test/resources/unused_code_analyzer/generated/**
    - test/resources/unnecessary_nullable_analyzer/generated/**
    - test/resources/file_path_folder/**
    - test/**/examples/**
    - "**/*.g.dart"
    - "**.freezed.dart"
    - "build/**"
    - "lib/generated/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - dart_code_linter

dart_code_linter:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 10
    maintainability-index: 50
    maximum-nesting: 5
    number-of-parameters: 5
    source-lines-of-code: 50
    halstead-volume: 150
    maximum-nesting-level: 5
    number-of-methods: 10
    technical-debt:
      threshold: 16
      todo-cost: 4
      ignore-cost: 8
      ignore-for-file-cost: 16
      as-dynamic-cost: 16
      deprecated-annotations-cost: 2
      file-nullsafety-migration-cost: 2
      unit-type: "hours"
  metrics-exclude:
    - test/src/analyzer_plugin/**
    - test/src/analyzers/**
    - test/src/cli/**
    - test/src/config_builder/**
    - test/src/helpers/**
    - test/src/reporters/**
    - test/src/utils/**
    - test/resources/*
    - test/*